workflows:
  build-apk:
    name: Build SignalScout APK
    environment:
      flutter: 3.22.0
    scripts:
      - flutter --version
      - flutter clean || true
      - flutter create --platforms=android .
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
