name: signal_scout
publish_to: "none"
description: Beautiful market signal dashboard for Android
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
